# Generated by Django 5.0 on 2024-01-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetabl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='день')),
                ('clas', models.CharField(max_length=50, verbose_name='класс')),
                ('uroki', models.CharField(max_length=200, verbose_name='уроки')),
            ],
        ),
    ]
